### ISSUE TITLE
[setup] PyMcaData gets installed at the wrong place

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#137]
Running pip install PyMca5 under windows one gets a directory PyMca5\PyMcaData at the python27 level and not inside python27\lib\site-packages\PyMca5

**Comment by PiRK** [comment]
After reading this long discussion https://github.com/pypa/pip/issues/2874, I get a feeling that `data_files` is  deprecated since pip 7.0.0. It does not properly work for projects which aim to be installable simply as `pip install project`. 

The suggestion in this discussion is that data meant to be packaged inside a wheel must be  declared as `package_data` in the `setup.py`. All data needed by the library are concerned. Only data such as Debian .desktop files should be shipped as data_files.

This is obviously incompatible with Debian packaging trying to keep data in a separate package from the library, in order to factor data for PY2 and PY3. 

Adopting the _silx_ (& _fabio_ & _PyFai_)  approach would be the simplest solution for long term maintenance. It would mean not supporting official Debian packaging at all in the `setup.py`, but rather instructing the packager to copy the data where they want and to patch the  `silx/resources/__init__.py` (https://github.com/silx-kit/silx/blob/master/silx/resources/__init__.py#L84) and `PyMca5/PyMcaDataDir.py` to tell the library where to find its data. 

When doing our own in-house Debian packaging, we obviously don't care that the data files end up copied inside the library, as we only have 1.6 Mb of data (~1Mb of which is material properties, and most of the rest is a few data files for training).

Would that be OK, @picca?

**Comment by vasole** [comment]
For Debian the current situation is not a problem as they **know** where the data will be installed and they set the PYMCA_DATA_DIR. 

The problem is for PyMca itself. The desired behavior is that if nobody says anything, the data directory should be installed inside the PyMca5 directory. It was because of that that we needed smart_install data.

The currently generated wheels work, but they write information at places they should not.

**Comment by picca** [comment]
I like the idea to maintain only a small patch in order to teach where to find the data.

If the setup.py is simpler (a lot) it is better for everyone.

cheers

**Comment by PiRK** [comment]
OK I believe that I did not really understand how `data_files`  works. It's obviously not meant to work together with `pip install`, it requires always specifying the location with `python setup.py --install-data ...` 

I need to revert `setup.py` back to before I started modifying it and find a solution that works both for `setup.py install` and `pip install`.

**Comment by vasole** [comment]
closed by #138
