### ISSUE TITLE
[plugins] XAS Normalization - Only one curve treated

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#150]
When taking the xanes2.h5 file (i.e. with multiple signals), the XAS normalization plugin applied in the silx window opened on a double click on an NXdata group, only shows one normalized curve.

**Comment by PiRK** [comment]
The plugin removes the last word in the curve's legend before prepending "Norm. ": https://github.com/vasole/pymca/blob/master/PyMca5/PyMcaPlugins/XASScanNormalizationPlugin.py#L206

in the regular MCA window, this works because all legends are multiple words (`"xanes2.h5 202.1 xmap_nika02 vs arr_energy" --> "xanes2.h5 202.1 xmap_nika02 vs"  --> "Nosm. xanes2.h5 202.1 xmap_nika02 vs"`)

In the NXdata viewer, the legends are single words (dataset names), so we end up with all newLegends being identical (`"xmap_nika06" --> "" --> "Norm. "` ). Only the last one remains plotted.

**Comment by PiRK** [comment]
The simplest solution would be to prepend "Norm. " to the entire legned, without removing a word.
