### ISSUE TITLE
[debian] No such file or directory: '/<<BUILDDIR>>/pymca-5.3.0+dfsg/PyMca5/PyMcaData/EPDL97/EADL.DAT'

### ISSUE THREAD

**Issue by picca** [vasole/pymca#205]
Hello,

I have some difficulties to understand this error.

WARNING: autodoc: failed to import module u'PyMca5.EPDL97.EADLSubshells'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc/importer.py", line 140, in import_module
    __import__(modname)
  File "/<<BUILDDIR>>/pymca-5.3.0+dfsg/.pybuild/cpython2_2.7_pymca5/build/PyMca5/EPDL97/__init__.py", line 65, in <module>
    from . import EADLParser, EADLSubshells, EPDL97Parser
  File "/<<BUILDDIR>>/pymca-5.3.0+dfsg/.pybuild/cpython2_2.7_pymca5/build/PyMca5/EPDL97/EADLParser.py", line 190, in <module>
    infile = open(EADL, 'rb')
IOError: [Errno 2] No such file or directory: '/<<BUILDDIR>>/pymca-5.3.0+dfsg/PyMca5/PyMcaData/EPDL97/EADL.DAT'

**Comment by picca** [comment]
In fact EPDL is not located in the PyMcaData directory. So when I ue the PYMCA_DATA_DIR, and set it to PyMcaData,it can not find it.

Is it possible to mode EPDL97 into PyMCAData this way the data are located at the right place ?

**Comment by vasole** [comment]
Yes, it is possible. lines 223-225 foresee in EPDL97Parser.py and 186-188 in EADLParser.py already foresee that possibility

**Comment by vasole** [comment]
@picca 

That module is in fact a set of scripts used to convert the EPDL97 format to a simpler format.  The converted files are already provided by the fisx library. Therefore the EPDL97 module can be deleted without affecting PyMca. I ship it with PyMca in order to allow people to know how to parse the original files and for transparency. I can see several options:

1. We do nothing and you copy EADL.DAT and EPDL97.DAT to PYMCA_DATA_DIR/EPDL97 during packaging
2. We duplicate EADL.DAT and EPDL97.DAT in PyMcaData/EPDL97
3. We do nothing and you remove the EPDL97 module during packaging
4. We move the complete EPDL97 module to third_party and you get rid of it as you do with everything under third party

I see options 1 and 4 as the cleanest.

**Comment by vasole** [comment]
@picca @PiRK 

I have checked and it seems everything was OK at your side because the EPDL97.DAT and EADL.DAT are properly located in setup.py. The problem was sphinx being confused by trying to run the scripts. This problem was therefore fixed by #208
