### ISSUE TITLE
please use pypi to distribute the pymca sources

### ISSUE THREAD

**Issue by picca** [vasole/pymca#27]
Hello, armando.

pip install seems to gain momentum, and people are expecting there software to be installable with pip.
On debian we are using more and more pypi as the source of our packages.
So in order to standardize around this, it would be great if you could upload pymca5 in pypi.

thanks a lot.

Ps: I am preparing 5.1.0 for debian experimental.
Now I am playing with the -dbg debug packages.

**Comment by vasole** [comment]
Hi Fred,

Now that PyQt wheels are available it makes sense to make PyMca pip installable. It is targeted for next release (5.1.2)

Armando

**Comment by picca** [comment]
Great armando, then I will use pypi as source for the package :)).

It think that I will be available for packaging during this summer :)
fisx and pymca.
It would be great to remove fisx from the pymca source and use the pip installation of fisx.
Until then I do some work around pyFAI with my trainee.

Cheers

Fred

**Comment by vasole** [comment]
The fisx sources distributed with PyMca are ignored by setup.py unless explicitly asked to be considered. They should not interfere with your default packaging.

They are there mainly for my convenience when generating ESRF debian packages because I can easily make fisx and PyMca share the same data (sub)package.

**Comment by picca** [comment]
You speak about all the data files used by fisx and pymca.

It would be great if pymca and fisx could share the same data whcih could come from another pacakge or decide which pacakge is the only one official source of the data fisx (from my point of viiew)

This way pymca should only depends on fisx in order to access the data and I could split fisx into

python-fisx
python3-fisx
python-fisx-common (for all the data installed under /usr/share/fisx/...)

that mean that at simple DATAPATH should be available in fisx in order to explain where are the data
so pymca could

DATAPATH = fisx.DATAPATH or something like this.



guidata and guiqwt use this sort of think.

I just need to maintain a one line patch in order to install all the data at the right place

Cheers


Fred

**Comment by vasole** [comment]
I am not against that proposal. Since fisx has no dependencies it should be easy to build. However, I think it will be a bit more complex to implement than it looks at first instance.

PyMca uses additional data so, probably either 

- I "contaminate" fisx with data that have nothing to do with it (ugly)
- Install PyMca data on the fisx data directory but I do not know how uninstall will behave
- Instruct PyMca to look for data in a list of directories instead of using just one directory

The later is probably the most error prone but probably better.

**Comment by picca** [comment]
>   *   I "contaminate" fisx with data that have nothing to do with it (ugly)

In thaht case the data should be split between
fisx data (/usr/share/fisx/...)
pymca data (/usr/share/pymca/...)

>   *   Install PyMca data on the fisx data directory but I do not know how uninstall will behave

This is not an issue for the pacakging but you are right this is ugly except if fisx propose and enhance data solution via a dedicated data path.
I mezan if fisx can use extra data provided by third party if they are installed in a dedicated directory.

>  *   Instruct PyMca to look for data in a list of directories instead of using just one directory

Pymca should finde the fisx data via fisx and it's own data by itself.

But I do not know exactly what your use from one sice and the other.

So maybe We should discuss more specifically on the rela data files and decide which one goes where :)

Cheers

**Comment by vasole** [comment]
- PyMca 5.1.2 available from PyPI.
- No duplication of data if fisx > 1.0.8 installed. If not, just one file is duplicated.
- fisx is now a mandatory dependency of PyMca.
