### ISSUE TITLE
Is it possible to distribute pymca data and fisx data on there own

### ISSUE THREAD

**Issue by picca** [vasole/pymca#29]
In order to avoid duplication of data, it would be great if fisx an dpymca5 would use a third party package, containing only the data.

**Comment by vasole** [comment]
On 29/08/2015 09:43, picca wrote:
>
> In order to avoid duplication of data, it would be great if fisx an 
> dpymca5 would use a third party package, containing only the data.
>

That is currently easily  achieved when building PyMca and fisx from the 
same setup.py

The package pymca-data would be a dependency for python-pymca5 and fisx. 
At the packaging time fisx could be presented as independent module.

Armando

**Comment by vasole** [comment]
Perhaps I misunderstood you and you were not considering "debian" packages (as I understood it) but "Python" packages....

**Comment by vasole** [comment]
@picca 

I have removed the duplicated files from PyMca and made the same changes as for fisx in order to allow you to set the directories via environment variables for testing.

There is a test that requires fisx to be installed in order to pass. I guess that should not be a problem because now fisx is a dependency of PyMca.

Please, could you start trying to pack current master branch to see if there are debian related problems?

**Comment by picca** [comment]
Hello armando.


can you produce an -rc1 and upload into pypi, this way I can check all the build process from the source and I can be sure thaht we are speaking of the same thing.

Cheers

Fred

**Comment by vasole** [comment]
It is the same work to produce the actual thing.

PyMca5 is in PyPI.

**Comment by vasole** [comment]
The address:

https://pypi.python.org/pypi/PyMca5
