### ISSUE TITLE
[ROI Imaging] Silx External Images Plugin

### ISSUE THREAD

**Issue by vasole** [vasole/pymca#341]
It would be convenient to be able to open multiple images in a single widget in order to allow to switch to scatter plots.

What is easier: to add the support of a background image into the old ExternalImages plugin or to adapt the Silx External Images plugin?

**Comment by PiRK** [comment]
The silx external images widget could theoretically load multiples background images, but all of the on the same  layer (multiple tiles with the bottom left corner at different origin). We limited the plugin to a single background image per widget because "crop", "rotate" and "flip" actions are only applied to the first loaded background image.

The widget can also load multiple foreground images, like the old widget. For foreground images, it is consistent with the old behavior, a single image is plotted and a slider enables browsing. 

The issue here is that the plugin has been designed to overlay the stack image on top of one or multiple backgrounds, so it always sets a single foreground image, and when multiple files are loaded, we assume that each one is a single background image.

One option would be to extend the plugin to provide two options: rather than only "Load images", we could provide "Load data files" (limited to images of the same shape as the stack) and "Load background images" (any size). 
And they we could add the scatter capability for foreground images.

**Comment by vasole** [comment]
OK. Then we have to think about other solution. In fact, the silx external images plugin should remain as it is and be used just to load background images (usually just one) that the other widgets can use.

Then the path to follow is to have the alternative roi window able to display a background image, associated motors, conditional median filter,...
