### ISSUE TITLE
Question about opening SPEC data file using ROI Imaging Tool

### ISSUE THREAD

**Issue by Henry0422** [vasole/pymca#38]
Hello,

Recently I wrote some code to export data in SPEC format file, but I couldn't let it opened in (PyMCA) ROI Imaging Tool. When I tried to open it in ROI Imaging Tool, it showed `File C  does not exists` and then it returned the error as following:

```
<type 'exceptions.ValueError'> 'axis' entry is out of bounds
please report details
'axis' entry is out of bounds   File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\PyMca5\PyMcaGui\pymca\QStackWidget.py", line 1166, in <module>
  File "build\PyMca5\PyMcaGui\pymca\QStackWidget.py", line 220, in setStack
  File "C:\Program Files\PyMca 5.1.2 (x64)\PyMca5\PyMcaCore\StackBase.py", line 245, in setStack
    self.stackUpdated()
  File "C:\Program Files\PyMca 5.1.2 (x64)\PyMca5\PyMcaCore\StackBase.py", line 262, in stackUpdated
    dtype=numpy.float)
  File "C:\Python27\lib\site-packages\numpy\core\fromnumeric.py", line 1848, in sum
  File "C:\Python27\lib\site-packages\numpy\core\_methods.py", line 32, in _sum
```

The data file is here: https://drive.google.com/file/d/0B8a9oC4tegPnQ3o0VzV2dnltcmc/view?usp=sharing
I really appropriate if someone could help me look into this.

Thanks.

**Comment by vasole** [comment]
Unless HDF5 is a heavy dependency for you, writing an HDF5 file with a 3D array containing all your MCAs might be simpler. Concerning your file:

- All lines have to end up with \n (no carriage return)
- In order to avoid buffer overflows, you should limit to 16 channel contents per line. So, you have to write a new line each 16 channel values qith the `\` character before the newline character like in:

```
@A 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 \
0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 \
....
```
and indicate that with a line `#@MCA %16C` in the header.

- You can add some lines to the header to indicate any calibration `#@CALIB` or channels if they do not start at zero  with the `#CHANN` line
```
#@MCA %16C
#@CHANN 4096 0 4095 1
#@CALIB 0 1 0
....
```
