### ISSUE TITLE
Windows build lacks HDF5 SWMR support

### ISSUE THREAD

**Issue by tschoonj** [vasole/pymca#46]
Hi Armando,

We have noticed that we cannot open our NXS files that were produced in SWMR mode with the currently available Windows build of PyMca. Since it works fine on our Linux systems which have access to HDF5 1.10.0, I guess the Windows build contains HDF5 1.8.x?

Thanks for looking into this,

Tom

**Comment by vasole** [comment]
I have never tested PyMca in SWMR mode. I thought I had to open the file in a different manner to make use of the SWMR feature but perhaps it was just for writing.

Please let me profit to ask for some feedback. Are you able to read the files generated with HDF5 1.10 on programs with HDF5 1.8?

**Comment by vasole** [comment]
Please, can you send me a file generated using SWMR so that I can test at my side?

I would not expect the SWMR feature to work under windows because it needs a POSIX file system. I assume the file was generated by a linux machine. If you need to make your file readable by older versions of the library, it seems you can use the tool described below. In any case, HDF5 1.10 could not be compiled under windows until the patch1 version was out.

Just some info from https://github.com/h5py/h5py/commit/404180c5ea673e554727eef098168fbafc05b1f5#commitcomment-19312456

Files created by 1.10.0 will be accessible by all newest versions.

SWMR feature uses new internal data structures that cannot be read by 1.8.* libraries, i.e., file created by SWMR cannot be read by application compiled with 1.8.

We provide h5format_convert tool that converts incompatible metadata in HDF5 file to 1.8 version. The tool does conversion in place,I.e, without rewriting raw data, so it is very efficient if you need to access the file created by SWMR by. 1.8 applications.
Please see SWMR documentation at support.hdfgroup.org or contact help@hdfgroup.org if you have any compatibility questions.
Don't be scared when you are using HDF5 :-)

**Comment by tschoonj** [comment]
Hi Armando,

I sent you an email with a link to two SWMR files for testing. These are indeed created on a Linux machine.

If I understand correctly it should be possible to read the SWMR files on Windows, just not create them.

**Comment by newville** [comment]
@tschoonj I think it depends greatly on the details of the filesystems used and how you access data from different machines.   From the HDFGroup's SWMR User Guide (Page 5, section 2):

> 
> To solve the difficulties involved with allowing concurrent access to write and read processes, HDF5 developers used an approach that is lock-free and that does not require any communication between processes.
>
> This approach is based on the assumption that the HDF5 file resides on a file system compliant with POSIX write semantics. The ordering feature of the POSIX write semantics is critical for the implementation: POSIX I/O writes must be performed in a sequentially consistent manner.
>
> These semantics apply to any processes that access the file from any location.
> The HDF5 SWMR feature was tested on Linux clusters with GPFS and Lustre, Linux systems with ext3/4, FreeBSD with UFS2, OS X with HFS+, and Windows with NTFS and GPFS. The SWMR feature does not work on network file systems (NFS, SMB/Windows file shares, and so on) since write ordering may not be preserved on those systems
> 

Perhaps you're doing something fancier at DLS, but for me "write on Linux, read from Windows" absolutely does not work (we use SMB/CIFS), even using 1.10 and modern versions of h5py throughout.    

We don't have GPFS or Lustre, so that "cannot use NFS, SMB..." is a very big deal for us.  Typical Epics areaDetectors run from dedicated linux (sometimes Windows) boxes supplied by the vendor, and we access the data via one of these not-Posix-enough-for-SMWR networked file systems.  So, SWMR can work on the machine collecting the data, but we really want to be able to read that data from some other machine, say to start displaying or processing the data while being collected.

I'd be interested to hear if you have a better solution.

**Comment by tschoonj** [comment]
Hi Matt,

I think my problem here is different: the SWMR HDF5 files have already been written and they are closed. Our staff and users just cannot open them for analysis with the current PyMca Windows release, which would involve simple read-only access. SWMR does modify the internals of the file compared to files written by 1.8.x (or 1.10.x but with SWMR turned off), but I think (I hope!) that the 1.10.x library can deal with this on Windows :smile:

**Comment by vasole** [comment]
If the point is "write on linux  read on windows while it is being written", indeed I do not see a solution. So any hint is welcome. We also have a lot of problems because of having to go through NFS.

@newville 
I have just been able to read Tom files with PyMca using HDF5 1.10.0patch1 So, I guess you meant you could not read from windows while the file being written.
If you need the h5py wheel I have (just) generated to test it I can make it available.

@tschoonj 
I am trying to figure out how to make a frozen binary of PyMca using that version because I could not compile the library with visual studio 2008 and I have never made a frozen binary with python 3.5.

**Comment by vasole** [comment]
Sorry Tom, your message arrived while typing. Yes, I can read your files under windows now but I have to figure out if I can generate a frozen binary. 

However that would only solve the problem with PyMca. According to the HDF Group, you should be able to run h5format_convert once you have finished writing the data to make the file compatible with HDF5 1.8

**Comment by jacobfilik** [comment]
Hi @vasole , @newville ,

Tom asked me to comment, the files written in SWMR mode are really not HDF5 files (in that they are not backwards compatible with the old HDF5 libraries). I feel they probably should have changed the extension to recognize this but they didn't.  We would like pyMCA to open the HDF5 files written in SWMR mode, but are not worried by it working when the file is still being written to, only that users can open the data after it is collected.

At Diamond the data writing and processing (which reads from the file) are all done across POSIX systems, for visualization we have a web server on one of the POSIX machines that responds to requests for slices of the data, reads the file and then serves the data back in some form (serialized java objects, jpegs etc...).

**Comment by newville** [comment]
@tschoonj  Oh, sorry for misunderstanding the problem. That definitely sounds like the "files written with SWMR and v 1.10 MUST be read with v. 1.10".    Relying on HDF5 is not scary at all!

**Comment by vasole** [comment]
Please, let me know if you can read your SWMR files with the frozen binary found at:

http://ftp.esrf.fr/pub/bliss/PyMca5.1.3-win64.exe

It works at my side, but since I have all the required libraries that does not warrant anything.

**Comment by vasole** [comment]
@newville 

I guess so. Honestly, I would not attempt to " inplace convert"  an acquisition file. Anything goes wrong and one looses precious data.

On the positive side, it seems if one does not use 1.10 features, files written with HDF5 1.10 can be read by HDF5 1.8. I have exported data using 1.10 and I can read them with 1.8. If that will always happen like that it remains to be seen.

**Comment by tschoonj** [comment]
@vasole seems to work fine! 

Many thanks for your quick and excellent work!

**Comment by vasole** [comment]
Well, I was fortunate to be able to compile HDF5 1.10.0-patch1 with Visual Studio 2008 in order to use the python 2.7 chain. I was unsuccessful on freezing PyMca under Python 3.5

I close the issue.
