### ISSUE TITLE
Linux install

### ISSUE THREAD

**Issue by mpmdean** [vasole/pymca#704]
Hi @vasole 

I have found pymca seems to have a subtle dependency that can cause issues installing into bare-bones linux environments.

More specifically, I had trouble adding pymca to this common, well-mainted docker container
https://hub.docker.com/r/jupyter/scipy-notebook
based on ubuntu.

I found that
`sudo apt-get install mesa-common-dev`
was needed. (This was confusing as the message implied a problem with gcc.)

Would you be okay with adding this small note to the bottom of the readme install instructions? I don't mind making the PR if you prefer?

**Comment by vasole** [comment]
It is true that the optional OpenGL capabilities of the program need the include file GL/gl.h during the build process of the whole package.

Debian and Ubuntu maintainers include mesa-common-dev during the build process of the package, but if you try to build PyMca from source yourself instead of using apt-get install pymca you will miss that file.

I am considering to provide that include file with the sources to remove that build time dependency...

**Comment by mpmdean** [comment]
`pip install pymca `
Can also fail with a not-super-clear error message if mesa-common-dev is missing.

**Comment by vasole** [comment]
setup.py checks the availability of the OpenGL headers. If they are not there the OpenGL extension modules are not built.
